import React, { useState } from "react";

import { ArrowRight, Info } from "lucide-react";
import { aiExplanationData } from "../../data/aiExplanationData";
import ModuleHeader from "../../component/RepositoryIntellihent/explaination/ModuleHeader";
import ExplanationTabs from "../../component/RepositoryIntellihent/explaination/ExplanationTabs";
import RiskFactorCard from "../../component/RepositoryIntellihent/explaination/RiskFactorCard";
import RecommendationCard from "../../component/RepositoryIntellihent/explaination/RecommendationCard";
import ImpactSummary, {
  Card,
} from "../../component/RepositoryIntellihent/explaination/ImpactSummary";
import QuickActions from "../../component/RepositoryIntellihent/explaination/QuickActions";
import RelatedIssues from "../../component/RepositoryIntellihent/explaination/RelatedIssues";
import { useParams, useSearchParams } from "react-router-dom";

const AIExplanation = () => {
  const [searchParams] = useSearchParams();

  const moduleName = searchParams.get("module");
  const [activeTab, setActiveTab] = useState("AI Explanation");

  const data = aiExplanationData;

  return (
    <div className="w-full space-y-3">
      <header>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">
          AI Explanation & Recommendations
        </h1>

        <p className="mt-1 text-[12px] text-slate-500">
          AI-generated explanation for risk prediction and personalized
          recommendations to improve code quality and architecture.
        </p>
      </header>

      <ModuleHeader module={data.module} />

      <ExplanationTabs activeTab={activeTab} onChange={setActiveTab} />

      {activeTab === "AI Explanation" && (
        <div className="grid grid-cols-1 gap-3 xl:grid-cols-[1fr_1fr_270px]">
          <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
            <div className="flex items-center justify-between">
              <h2 className="text-[11px] font-bold text-slate-800">
                AI Explanation
                <span className="font-normal text-slate-500">
                  (Why is this module high risk?)
                </span>
              </h2>

              <span className="rounded-md bg-purple-50 px-2 py-1 text-[9px] font-semibold text-purple-600">
                Generated by Llama 3
              </span>
            </div>

            <p className="mt-3 text-[10px] leading-4 text-slate-600 italic">
              PaymentService is predicted as high risk for architecture drift
              based on multiple factors observed in both its current state and
              recent evolution.
            </p>

            <div className="mt-3">
              {data.factors.map((factor) => (
                <RiskFactorCard key={factor.title} factor={factor} />
              ))}
            </div>

            <div className="mt-3 flex items-center justify-between rounded-md border border-slate-200 bg-slate-50 px-3 py-2">
              <span className="text-[10px] font-semibold text-slate-600">
                Overall Drift Contribution
              </span>

              <span className="rounded-md bg-red-50 px-2 py-1 text-[10px] font-bold text-red-500">
                +0.89 (High Risk)
              </span>
            </div>

            <div className="mt-3 rounded-md border border-blue-100 bg-blue-50/40 px-3 py-2">
              <p className="flex items-center gap-2 text-[9px] text-blue-700">
                <Info size={10} />
                This explanation is generated using HRIM prediction, SHAP
                values, and repository knowledge graph.
              </p>
            </div>
          </section>

          <section className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">
            <div className="flex items-center justify-between">
              <h2 className="text-[11px] font-bold text-slate-800">
                AI Recommendations
                <span className="font-normal text-slate-500">
                  {" "}
                  (What should be done?)
                </span>
              </h2>

              <select className="rounded-md border border-slate-200 bg-white px-2 py-1 text-[10px] text-slate-600">
                <option>Priority</option>
                <option>Impact</option>
                <option>Effort</option>
              </select>
            </div>

            <div className="mt-2">
              {data.recommendations.map((recommendation) => (
                <RecommendationCard
                  key={recommendation.number}
                  recommendation={recommendation}
                />
              ))}
            </div>

            <button className="mt-3 flex items-center gap-1 text-[10px] font-semibold text-blue-600">
              See all recommendations
              <ArrowRight size={11} />
            </button>
          </section>

          <aside className="space-y-3">
            <ImpactSummary items={data.impact} />

            <QuickActions />

            <RelatedIssues issues={data.relatedIssues} />

            <Card title="Related High-Risk Modules" action="View All (3)">
              <div className="space-y-3">
                {data.relatedModules.map((module) => (
                  <div
                    key={module.name}
                    className="flex items-center justify-between"
                  >
                    <span className="text-[10px] font-semibold text-slate-700">
                      {module.name}
                    </span>

                    <div className="flex items-center gap-2">
                      <span className="text-[9px] text-slate-500">
                        Risk: {module.risk}
                      </span>

                      <span className="rounded bg-red-50 px-2 py-1 text-[9px] font-semibold text-red-500">
                        {module.severity}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </Card>

            <Card title="Explanation History" action="View All">
              <div className="space-y-3">
                {data.history.map((item) => (
                  <div
                    key={item.date}
                    className="flex items-center justify-between gap-2"
                  >
                    <div>
                      <p className="text-[9px] text-slate-500">{item.date}</p>

                      <p className="text-[10px] font-medium text-slate-700">
                        {item.model}
                      </p>
                    </div>

                    <span className="rounded bg-red-50 px-2 py-1 text-[9px] font-semibold text-red-500">
                      {item.severity}
                    </span>
                  </div>
                ))}
              </div>
            </Card>
          </aside>
        </div>
      )}

      {activeTab === "Recommendations" && (
        <RecommendationsView recommendations={data.recommendations} />
      )}

      {activeTab === "Evidence & Context" && (
        <PlaceholderView
          title="Evidence & Context"
          description="Repository evidence, code references and knowledge graph context will appear here."
        />
      )}

      {activeTab === "Metrics Impact" && (
        <PlaceholderView
          title="Metrics Impact"
          description="Detailed metric contribution and historical impact analysis."
        />
      )}

      {activeTab === "Similar Modules" && (
        <PlaceholderView
          title="Similar Modules"
          description="Modules with similar architecture and risk characteristics."
        />
      )}
    </div>
  );
};

const RecommendationsView = ({ recommendations }) => {
  return (
    <section className="rounded-xl border border-slate-200 bg-white p-4">
      <h2 className="text-sm font-bold text-slate-800">AI Recommendations</h2>

      <div className="mt-3 divide-y divide-slate-100">
        {recommendations.map((item) => (
          <RecommendationCard key={item.number} recommendation={item} />
        ))}
      </div>
    </section>
  );
};

const PlaceholderView = ({ title, description }) => {
  return (
    <section className="flex min-h-[400px] items-center justify-center rounded-xl border border-slate-200 bg-white">
      <div className="text-center">
        <Info size={30} className="mx-auto text-slate-300" />

        <h2 className="mt-3 text-sm font-bold text-slate-800">{title}</h2>

        <p className="mt-1 max-w-md text-[9px] text-slate-500">{description}</p>
      </div>
    </section>
  );
};

export default AIExplanation;
